### ISSUE TITLE
idf.py build error

### ISSUE THREAD

**Issue by DannyRhinez** [playduck/esp32_bluetooth_dsp#1]
Current build issues present due to deprecation issues?
[BuildErrors.txt](https://github.com/playduck/esp32-bluetooth-dsp/files/12707811/BuildErrors.txt)

**Comment by playduck** [comment]
The code still builds on the original idf version I've used (idf-v4.4).
However you're right it does clash a bit with the latest v5.1.1.

If addressed those issues on the [idf-v5.1.1 branch](https://github.com/playduck/esp32-bluetooth-dsp/tree/idf-v5.1.1).
You need to pull the latest master of the dsp-playground as well, as it caused some weird linker problems.
Also I was lazy and used the FreeRTOS backwards compatability API, so that must be enabled in the menuconfig too (`COMPONENT CONFIG > FreeRTOS > Kernel > configENABLE_BACKWARD_COMPATIBILITY`).
Perhaps this should be re-written for the more modern api.

I don't have access to the hardware right now, could you check if this still works?

**Comment by DannyRhinez** [comment]
FYI Using an ESP32-WROOM-32D module. Idk if that'll pose problems

**Comment by DannyRhinez** [comment]
Still seeing build issues using v5.1.1. looks largely like compilation warnings for uninitialized and some deprecated I2S APIs?

[BuildIssues v5.1.1.txt](https://github.com/playduck/esp32-bluetooth-dsp/files/12707986/BuildIssues.v5.1.1.txt)

**Comment by DannyRhinez** [comment]
Nevermind -- Pulled latest dsp-playground, and compiled w/ Linux Mint using v5.1.1

Thank you so much <3
